FROM amazoncorretto:11-alpine-jdk as builder

WORKDIR .

COPY gradlew .
COPY gradle gradle
COPY build.gradle.kts .
COPY settings.gradle.kts .
COPY src src

RUN chmod +x ./gradlew
RUN ./gradlew bootJar

FROM amazoncorretto:11-alpine-jdk

WORKDIR .

EXPOSE 8080

ARG JAR_FILE=build/libs/hongit-0.0.1-SNAPSHOT.jar

COPY --from=builder ${JAR_FILE} hongit-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=dev", "-jar", "/hongit-0.0.1-SNAPSHOT.jar"]
