FROM amazoncorretto:11-alpine-jdk

VOLUME /tmp

EXPOSE 8080

ARG JAR_FILE=build/libs/untitled-0.0.1-SNAPSHOT.jar

COPY ${JAR_FILE} untitled-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=dev", "-jar", "/untitled-0.0.1-SNAPSHOT.jar"]
