FROM amazoncorretto:11-alpine-jdk as builder

WORKDIR .

COPY gradlew .
COPY gradle gradle
COPY build.gradle.kts .
COPY settings.gradle.kts .
COPY gradle.properties .
COPY buildSrc buildSrc
COPY clients clients
COPY hongit-api hongit-api
COPY hongit-core hongit-core
COPY hongit-secret hongit-secret

RUN chmod +x ./gradlew
RUN ./gradlew hongit-api:bootJar

FROM amazoncorretto:11-alpine-jdk

WORKDIR .

EXPOSE 8080

ARG JAR_FILE=hongit-api/build/libs/hongit-api-1.0.0.jar

COPY --from=builder ${JAR_FILE} hongit-api-1.0.0.jar

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=dev", "-jar", "/hongit-api-1.0.0.jar"]
