spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

mail:
  sender:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    protocol: smtp
    auth: true
    starttls-enable: true
    starttls-required: true
    debug: true
    connection-timeout: 5000
    timeout: 5000
    write-timeout: 5000
