spring:
  config:
    import:
      - classpath:application-mail.yml
      - classpath:application-aws-s3.yml
      - classpath:application-secret.yml
  profiles:
    include:
      - db
      - common

---

spring:
  config:
    activate:
      on-profile: db

  datasource:
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

---

spring:
  config:
    activate:
      on-profile: common

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  config: classpath:log4j2.yml
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql: trace

---

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mariadb://localhost:3306/hongit

---

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mariadb://hongit_database:3306/hongit

logging:
  config: classpath:log4j2-dev.yml

---

spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mariadb://hongit_database:3306/hongit

logging:
  config: classpath:log4j2-prod.yml
  level:
    org.hibernate:
      SQL: info
      type.descriptor.sql: info
