spring:
  profiles:
    include:
      - common

---

spring:
  config:
    activate:
      on-profile: common
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

mail:
  sender:
    mode: stub
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    protocol: smtp
    auth: true
    starttls-enable: true
    starttls-required: true
    debug: true
    connection-timeout: 5000
    timeout: 5000
    write-timeout: 5000


---

spring:
  config:
    activate:
      on-profile: local

mail:
  sender:
    mode: stub

---

spring:
  config:
    activate:
      on-profile: dev

mail:
  sender:
    mode: stub

---

spring:
  config:
    activate:
      on-profile: prod

mail:
  sender:
    mode: prod
