spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false

mail:
  sender:
    host: smtp.gmail.com
    port: 587
    username: hello
    password: 1234
    protocol: smtp
    auth: true
    starttls-enable: true
    starttls-required: true
    debug: true
    connection-timeout: 5000
    timeout: 5000
    write-timeout: 5000
